### ISSUE TITLE
Add the ability for people to look up other users wishlists

### ISSUE THREAD

**Issue by AnthonyRobertson17** [AnthonyRobertson17/arob#275]
# Tasks
- [ ] Update the show views for wishlists and wishlist items to only show edit/create controls when the owner is viewing the wishlist
- [ ] Review all changes and update test coverage
- [ ] Go through all the places where there are links and apply the new link underline class
- [ ] Put up and merge PR
