### ISSUE TITLE
Add Exercise types

### ISSUE THREAD

**Issue by AnthonyRobertson17** [AnthonyRobertson17/arob#90]
- [x] Create model for exercise types
- [x] Create model for exercise type tags
- [x] Create model for exercise type tag assignments
- [x] Exercise type tag CRUD
- [x] Add exercise type tags to the "all tags" page
- [x] Exercise type CRUD
